/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PmsRouteImport } from './routes/pms'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminBookingsRouteImport } from './routes/admin_.bookings'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as PmsIndexRouteImport } from './routes/pms.index'
import { Route as PmsAirbnbSpacesRouteImport } from './routes/pms.airbnb-spaces'
import { Route as PmsBookingsRouteImport } from './routes/pms.bookings'
import { Route as PmsCaretakerRouteImport } from './routes/pms.caretaker'
import { Route as PmsExpensesRouteImport } from './routes/pms.expenses'
import { Route as PmsInquiriesRouteImport } from './routes/pms.inquiries'
import { Route as PmsInventoryRouteImport } from './routes/pms.inventory'
import { Route as PmsInvoicesRouteImport } from './routes/pms.invoices'
import { Route as PmsPosRouteImport } from './routes/pms.pos'
import { Route as PmsSettingsRouteImport } from './routes/pms.settings'
import { Route as PmsSuperAdminRouteImport } from './routes/pms.super-admin'
import { Route as PmsSystemRouteImport } from './routes/pms.system'
import { Route as PmsVouchersRouteImport } from './routes/pms.vouchers'
import { Route as PmsLoginRouteImport } from './routes/pms_.login'
import { Route as PmsOnboardingRouteImport } from './routes/pms_.onboarding'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as StaysLargeGroupsRouteImport } from './routes/stays_.large-groups'
import { Route as StaysPrivatePoolVillasRouteImport } from './routes/stays_.private-pool-villas'
import { Route as PmsInvoicesNewRouteImport } from './routes/pms.invoices_.new'
import { Route as PmsPosIndexRouteImport } from './routes/pms.pos.index'
import { Route as PmsPosHelpRouteImport } from './routes/pms.pos.help'
import { Route as PmsPosManageRouteImport } from './routes/pms.pos.manage'
import { Route as PmsPosOrdersRouteImport } from './routes/pms.pos.orders'
import { Route as PmsPosQuickRouteImport } from './routes/pms.pos.quick'
import { Route as PmsPosReportsRouteImport } from './routes/pms.pos.reports'
import { Route as PmsPosSettingsRouteImport } from './routes/pms.pos.settings'
import { Route as PmsSettingsUsersRouteImport } from './routes/pms.settings_.users'
import { Route as PmsAuthCallbackRouteImport } from './routes/pms_.auth.callback'
import { Route as PmsAuthGoogleStartRouteImport } from './routes/pms_.auth.google-start'
import { Route as PmsPosManageIndexRouteImport } from './routes/pms.pos.manage.index'
import { Route as PmsPosManageActivityLogsRouteImport } from './routes/pms.pos.manage.activity-logs'
import { Route as PmsPosManageCategoriesRouteImport } from './routes/pms.pos.manage.categories'
import { Route as PmsPosManageCustomersRouteImport } from './routes/pms.pos.manage.customers'
import { Route as PmsPosManageEmployeesRouteImport } from './routes/pms.pos.manage.employees'
import { Route as PmsPosManageIncomeExpenseRouteImport } from './routes/pms.pos.manage.income-expense'
import { Route as PmsPosManageInvoicesRouteImport } from './routes/pms.pos.manage.invoices'
import { Route as PmsPosManageItemsRouteImport } from './routes/pms.pos.manage.items'
import { Route as PmsPosSettingsIndexRouteImport } from './routes/pms.pos.settings.index'
import { Route as PmsPosSettingsDiscountsRouteImport } from './routes/pms.pos.settings.discounts'
import { Route as PmsPosSettingsDisplayRouteImport } from './routes/pms.pos.settings.display'
import { Route as PmsPosSettingsGeneralRouteImport } from './routes/pms.pos.settings.general'
import { Route as PmsPosSettingsPaymentTaxRouteImport } from './routes/pms.pos.settings.payment-tax'
import { Route as PmsPosSettingsPrintersRouteImport } from './routes/pms.pos.settings.printers'
import { Route as PmsPosSettingsStationsRouteImport } from './routes/pms.pos.settings.stations'
import { Route as PmsPosSettingsStoreRouteImport } from './routes/pms.pos.settings.store'
import { Route as PmsPosSettingsTableGroupsRouteImport } from './routes/pms.pos.settings.table-groups'
import { Route as PmsPosSettingsUtilityRouteImport } from './routes/pms.pos.settings.utility'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsRoute = PmsRouteImport.update({
  id: '/pms',
  path: '/pms',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin_/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsIndexRoute = PmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmsRoute,
} as any)
const PmsAirbnbSpacesRoute = PmsAirbnbSpacesRouteImport.update({
  id: '/airbnb-spaces',
  path: '/airbnb-spaces',
  getParentRoute: () => PmsRoute,
} as any)
const PmsBookingsRoute = PmsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PmsRoute,
} as any)
const PmsCaretakerRoute = PmsCaretakerRouteImport.update({
  id: '/caretaker',
  path: '/caretaker',
  getParentRoute: () => PmsRoute,
} as any)
const PmsExpensesRoute = PmsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => PmsRoute,
} as any)
const PmsInquiriesRoute = PmsInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => PmsRoute,
} as any)
const PmsInventoryRoute = PmsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PmsRoute,
} as any)
const PmsInvoicesRoute = PmsInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PmsRoute,
} as any)
const PmsPosRoute = PmsPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => PmsRoute,
} as any)
const PmsSettingsRoute = PmsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PmsRoute,
} as any)
const PmsSuperAdminRoute = PmsSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => PmsRoute,
} as any)
const PmsSystemRoute = PmsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => PmsRoute,
} as any)
const PmsVouchersRoute = PmsVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => PmsRoute,
} as any)
const PmsLoginRoute = PmsLoginRouteImport.update({
  id: '/pms_/login',
  path: '/pms/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsOnboardingRoute = PmsOnboardingRouteImport.update({
  id: '/pms_/onboarding',
  path: '/pms/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysLargeGroupsRoute = StaysLargeGroupsRouteImport.update({
  id: '/stays_/large-groups',
  path: '/stays/large-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysPrivatePoolVillasRoute = StaysPrivatePoolVillasRouteImport.update({
  id: '/stays_/private-pool-villas',
  path: '/stays/private-pool-villas',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsInvoicesNewRoute = PmsInvoicesNewRouteImport.update({
  id: '/invoices_/new',
  path: '/invoices/new',
  getParentRoute: () => PmsRoute,
} as any)
const PmsPosIndexRoute = PmsPosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsPosHelpRoute = PmsPosHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsPosManageRoute = PmsPosManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsPosOrdersRoute = PmsPosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsPosQuickRoute = PmsPosQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsPosReportsRoute = PmsPosReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsPosSettingsRoute = PmsPosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PmsPosRoute,
} as any)
const PmsSettingsUsersRoute = PmsSettingsUsersRouteImport.update({
  id: '/settings_/users',
  path: '/settings/users',
  getParentRoute: () => PmsRoute,
} as any)
const PmsAuthCallbackRoute = PmsAuthCallbackRouteImport.update({
  id: '/pms_/auth/callback',
  path: '/pms/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsAuthGoogleStartRoute = PmsAuthGoogleStartRouteImport.update({
  id: '/pms_/auth/google-start',
  path: '/pms/auth/google-start',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsPosManageIndexRoute = PmsPosManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmsPosManageRoute,
} as any)
const PmsPosManageActivityLogsRoute =
  PmsPosManageActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => PmsPosManageRoute,
  } as any)
const PmsPosManageCategoriesRoute = PmsPosManageCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PmsPosManageRoute,
} as any)
const PmsPosManageCustomersRoute = PmsPosManageCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PmsPosManageRoute,
} as any)
const PmsPosManageEmployeesRoute = PmsPosManageEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PmsPosManageRoute,
} as any)
const PmsPosManageIncomeExpenseRoute =
  PmsPosManageIncomeExpenseRouteImport.update({
    id: '/income-expense',
    path: '/income-expense',
    getParentRoute: () => PmsPosManageRoute,
  } as any)
const PmsPosManageInvoicesRoute = PmsPosManageInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PmsPosManageRoute,
} as any)
const PmsPosManageItemsRoute = PmsPosManageItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => PmsPosManageRoute,
} as any)
const PmsPosSettingsIndexRoute = PmsPosSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsDiscountsRoute = PmsPosSettingsDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsDisplayRoute = PmsPosSettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsGeneralRoute = PmsPosSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsPaymentTaxRoute =
  PmsPosSettingsPaymentTaxRouteImport.update({
    id: '/payment-tax',
    path: '/payment-tax',
    getParentRoute: () => PmsPosSettingsRoute,
  } as any)
const PmsPosSettingsPrintersRoute = PmsPosSettingsPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsStationsRoute = PmsPosSettingsStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsStoreRoute = PmsPosSettingsStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)
const PmsPosSettingsTableGroupsRoute =
  PmsPosSettingsTableGroupsRouteImport.update({
    id: '/table-groups',
    path: '/table-groups',
    getParentRoute: () => PmsPosSettingsRoute,
  } as any)
const PmsPosSettingsUtilityRoute = PmsPosSettingsUtilityRouteImport.update({
  id: '/utility',
  path: '/utility',
  getParentRoute: () => PmsPosSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pms': typeof PmsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/pms/airbnb-spaces': typeof PmsAirbnbSpacesRoute
  '/pms/bookings': typeof PmsBookingsRoute
  '/pms/caretaker': typeof PmsCaretakerRoute
  '/pms/expenses': typeof PmsExpensesRoute
  '/pms/inquiries': typeof PmsInquiriesRoute
  '/pms/inventory': typeof PmsInventoryRoute
  '/pms/invoices': typeof PmsInvoicesRoute
  '/pms/pos': typeof PmsPosRouteWithChildren
  '/pms/settings': typeof PmsSettingsRoute
  '/pms/super-admin': typeof PmsSuperAdminRoute
  '/pms/system': typeof PmsSystemRoute
  '/pms/vouchers': typeof PmsVouchersRoute
  '/pms/login': typeof PmsLoginRoute
  '/pms/onboarding': typeof PmsOnboardingRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/stays/large-groups': typeof StaysLargeGroupsRoute
  '/stays/private-pool-villas': typeof StaysPrivatePoolVillasRoute
  '/blog/': typeof BlogIndexRoute
  '/pms/': typeof PmsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/pms/invoices/new': typeof PmsInvoicesNewRoute
  '/pms/pos/help': typeof PmsPosHelpRoute
  '/pms/pos/manage': typeof PmsPosManageRouteWithChildren
  '/pms/pos/orders': typeof PmsPosOrdersRoute
  '/pms/pos/quick': typeof PmsPosQuickRoute
  '/pms/pos/reports': typeof PmsPosReportsRoute
  '/pms/pos/settings': typeof PmsPosSettingsRouteWithChildren
  '/pms/settings/users': typeof PmsSettingsUsersRoute
  '/pms/auth/callback': typeof PmsAuthCallbackRoute
  '/pms/auth/google-start': typeof PmsAuthGoogleStartRoute
  '/pms/pos/': typeof PmsPosIndexRoute
  '/pms/pos/manage/activity-logs': typeof PmsPosManageActivityLogsRoute
  '/pms/pos/manage/categories': typeof PmsPosManageCategoriesRoute
  '/pms/pos/manage/customers': typeof PmsPosManageCustomersRoute
  '/pms/pos/manage/employees': typeof PmsPosManageEmployeesRoute
  '/pms/pos/manage/income-expense': typeof PmsPosManageIncomeExpenseRoute
  '/pms/pos/manage/invoices': typeof PmsPosManageInvoicesRoute
  '/pms/pos/manage/items': typeof PmsPosManageItemsRoute
  '/pms/pos/settings/discounts': typeof PmsPosSettingsDiscountsRoute
  '/pms/pos/settings/display': typeof PmsPosSettingsDisplayRoute
  '/pms/pos/settings/general': typeof PmsPosSettingsGeneralRoute
  '/pms/pos/settings/payment-tax': typeof PmsPosSettingsPaymentTaxRoute
  '/pms/pos/settings/printers': typeof PmsPosSettingsPrintersRoute
  '/pms/pos/settings/stations': typeof PmsPosSettingsStationsRoute
  '/pms/pos/settings/store': typeof PmsPosSettingsStoreRoute
  '/pms/pos/settings/table-groups': typeof PmsPosSettingsTableGroupsRoute
  '/pms/pos/settings/utility': typeof PmsPosSettingsUtilityRoute
  '/pms/pos/manage/': typeof PmsPosManageIndexRoute
  '/pms/pos/settings/': typeof PmsPosSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/pms/airbnb-spaces': typeof PmsAirbnbSpacesRoute
  '/pms/bookings': typeof PmsBookingsRoute
  '/pms/caretaker': typeof PmsCaretakerRoute
  '/pms/expenses': typeof PmsExpensesRoute
  '/pms/inquiries': typeof PmsInquiriesRoute
  '/pms/inventory': typeof PmsInventoryRoute
  '/pms/invoices': typeof PmsInvoicesRoute
  '/pms/settings': typeof PmsSettingsRoute
  '/pms/super-admin': typeof PmsSuperAdminRoute
  '/pms/system': typeof PmsSystemRoute
  '/pms/vouchers': typeof PmsVouchersRoute
  '/pms/login': typeof PmsLoginRoute
  '/pms/onboarding': typeof PmsOnboardingRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/stays/large-groups': typeof StaysLargeGroupsRoute
  '/stays/private-pool-villas': typeof StaysPrivatePoolVillasRoute
  '/blog': typeof BlogIndexRoute
  '/pms': typeof PmsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/pms/invoices/new': typeof PmsInvoicesNewRoute
  '/pms/pos/help': typeof PmsPosHelpRoute
  '/pms/pos/orders': typeof PmsPosOrdersRoute
  '/pms/pos/quick': typeof PmsPosQuickRoute
  '/pms/pos/reports': typeof PmsPosReportsRoute
  '/pms/settings/users': typeof PmsSettingsUsersRoute
  '/pms/auth/callback': typeof PmsAuthCallbackRoute
  '/pms/auth/google-start': typeof PmsAuthGoogleStartRoute
  '/pms/pos': typeof PmsPosIndexRoute
  '/pms/pos/manage/activity-logs': typeof PmsPosManageActivityLogsRoute
  '/pms/pos/manage/categories': typeof PmsPosManageCategoriesRoute
  '/pms/pos/manage/customers': typeof PmsPosManageCustomersRoute
  '/pms/pos/manage/employees': typeof PmsPosManageEmployeesRoute
  '/pms/pos/manage/income-expense': typeof PmsPosManageIncomeExpenseRoute
  '/pms/pos/manage/invoices': typeof PmsPosManageInvoicesRoute
  '/pms/pos/manage/items': typeof PmsPosManageItemsRoute
  '/pms/pos/settings/discounts': typeof PmsPosSettingsDiscountsRoute
  '/pms/pos/settings/display': typeof PmsPosSettingsDisplayRoute
  '/pms/pos/settings/general': typeof PmsPosSettingsGeneralRoute
  '/pms/pos/settings/payment-tax': typeof PmsPosSettingsPaymentTaxRoute
  '/pms/pos/settings/printers': typeof PmsPosSettingsPrintersRoute
  '/pms/pos/settings/stations': typeof PmsPosSettingsStationsRoute
  '/pms/pos/settings/store': typeof PmsPosSettingsStoreRoute
  '/pms/pos/settings/table-groups': typeof PmsPosSettingsTableGroupsRoute
  '/pms/pos/settings/utility': typeof PmsPosSettingsUtilityRoute
  '/pms/pos/manage': typeof PmsPosManageIndexRoute
  '/pms/pos/settings': typeof PmsPosSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pms': typeof PmsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRoute
  '/terms': typeof TermsRoute
  '/admin_/bookings': typeof AdminBookingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/pms/airbnb-spaces': typeof PmsAirbnbSpacesRoute
  '/pms/bookings': typeof PmsBookingsRoute
  '/pms/caretaker': typeof PmsCaretakerRoute
  '/pms/expenses': typeof PmsExpensesRoute
  '/pms/inquiries': typeof PmsInquiriesRoute
  '/pms/inventory': typeof PmsInventoryRoute
  '/pms/invoices': typeof PmsInvoicesRoute
  '/pms/pos': typeof PmsPosRouteWithChildren
  '/pms/settings': typeof PmsSettingsRoute
  '/pms/super-admin': typeof PmsSuperAdminRoute
  '/pms/system': typeof PmsSystemRoute
  '/pms/vouchers': typeof PmsVouchersRoute
  '/pms_/login': typeof PmsLoginRoute
  '/pms_/onboarding': typeof PmsOnboardingRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/stays_/large-groups': typeof StaysLargeGroupsRoute
  '/stays_/private-pool-villas': typeof StaysPrivatePoolVillasRoute
  '/blog/': typeof BlogIndexRoute
  '/pms/': typeof PmsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/pms/invoices_/new': typeof PmsInvoicesNewRoute
  '/pms/pos/help': typeof PmsPosHelpRoute
  '/pms/pos/manage': typeof PmsPosManageRouteWithChildren
  '/pms/pos/orders': typeof PmsPosOrdersRoute
  '/pms/pos/quick': typeof PmsPosQuickRoute
  '/pms/pos/reports': typeof PmsPosReportsRoute
  '/pms/pos/settings': typeof PmsPosSettingsRouteWithChildren
  '/pms/settings_/users': typeof PmsSettingsUsersRoute
  '/pms_/auth/callback': typeof PmsAuthCallbackRoute
  '/pms_/auth/google-start': typeof PmsAuthGoogleStartRoute
  '/pms/pos/': typeof PmsPosIndexRoute
  '/pms/pos/manage/activity-logs': typeof PmsPosManageActivityLogsRoute
  '/pms/pos/manage/categories': typeof PmsPosManageCategoriesRoute
  '/pms/pos/manage/customers': typeof PmsPosManageCustomersRoute
  '/pms/pos/manage/employees': typeof PmsPosManageEmployeesRoute
  '/pms/pos/manage/income-expense': typeof PmsPosManageIncomeExpenseRoute
  '/pms/pos/manage/invoices': typeof PmsPosManageInvoicesRoute
  '/pms/pos/manage/items': typeof PmsPosManageItemsRoute
  '/pms/pos/settings/discounts': typeof PmsPosSettingsDiscountsRoute
  '/pms/pos/settings/display': typeof PmsPosSettingsDisplayRoute
  '/pms/pos/settings/general': typeof PmsPosSettingsGeneralRoute
  '/pms/pos/settings/payment-tax': typeof PmsPosSettingsPaymentTaxRoute
  '/pms/pos/settings/printers': typeof PmsPosSettingsPrintersRoute
  '/pms/pos/settings/stations': typeof PmsPosSettingsStationsRoute
  '/pms/pos/settings/store': typeof PmsPosSettingsStoreRoute
  '/pms/pos/settings/table-groups': typeof PmsPosSettingsTableGroupsRoute
  '/pms/pos/settings/utility': typeof PmsPosSettingsUtilityRoute
  '/pms/pos/manage/': typeof PmsPosManageIndexRoute
  '/pms/pos/settings/': typeof PmsPosSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking-success'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/pms'
    | '/portal'
    | '/privacy'
    | '/signup'
    | '/stays'
    | '/terms'
    | '/admin/bookings'
    | '/blog/$slug'
    | '/locations/$slug'
    | '/pms/airbnb-spaces'
    | '/pms/bookings'
    | '/pms/caretaker'
    | '/pms/expenses'
    | '/pms/inquiries'
    | '/pms/inventory'
    | '/pms/invoices'
    | '/pms/pos'
    | '/pms/settings'
    | '/pms/super-admin'
    | '/pms/system'
    | '/pms/vouchers'
    | '/pms/login'
    | '/pms/onboarding'
    | '/portal/dashboard'
    | '/portal/login'
    | '/properties/$slug'
    | '/stays/large-groups'
    | '/stays/private-pool-villas'
    | '/blog/'
    | '/pms/'
    | '/portal/'
    | '/pms/invoices/new'
    | '/pms/pos/help'
    | '/pms/pos/manage'
    | '/pms/pos/orders'
    | '/pms/pos/quick'
    | '/pms/pos/reports'
    | '/pms/pos/settings'
    | '/pms/settings/users'
    | '/pms/auth/callback'
    | '/pms/auth/google-start'
    | '/pms/pos/'
    | '/pms/pos/manage/activity-logs'
    | '/pms/pos/manage/categories'
    | '/pms/pos/manage/customers'
    | '/pms/pos/manage/employees'
    | '/pms/pos/manage/income-expense'
    | '/pms/pos/manage/invoices'
    | '/pms/pos/manage/items'
    | '/pms/pos/settings/discounts'
    | '/pms/pos/settings/display'
    | '/pms/pos/settings/general'
    | '/pms/pos/settings/payment-tax'
    | '/pms/pos/settings/printers'
    | '/pms/pos/settings/stations'
    | '/pms/pos/settings/store'
    | '/pms/pos/settings/table-groups'
    | '/pms/pos/settings/utility'
    | '/pms/pos/manage/'
    | '/pms/pos/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking-success'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/signup'
    | '/stays'
    | '/terms'
    | '/admin/bookings'
    | '/blog/$slug'
    | '/locations/$slug'
    | '/pms/airbnb-spaces'
    | '/pms/bookings'
    | '/pms/caretaker'
    | '/pms/expenses'
    | '/pms/inquiries'
    | '/pms/inventory'
    | '/pms/invoices'
    | '/pms/settings'
    | '/pms/super-admin'
    | '/pms/system'
    | '/pms/vouchers'
    | '/pms/login'
    | '/pms/onboarding'
    | '/portal/dashboard'
    | '/portal/login'
    | '/properties/$slug'
    | '/stays/large-groups'
    | '/stays/private-pool-villas'
    | '/blog'
    | '/pms'
    | '/portal'
    | '/pms/invoices/new'
    | '/pms/pos/help'
    | '/pms/pos/orders'
    | '/pms/pos/quick'
    | '/pms/pos/reports'
    | '/pms/settings/users'
    | '/pms/auth/callback'
    | '/pms/auth/google-start'
    | '/pms/pos'
    | '/pms/pos/manage/activity-logs'
    | '/pms/pos/manage/categories'
    | '/pms/pos/manage/customers'
    | '/pms/pos/manage/employees'
    | '/pms/pos/manage/income-expense'
    | '/pms/pos/manage/invoices'
    | '/pms/pos/manage/items'
    | '/pms/pos/settings/discounts'
    | '/pms/pos/settings/display'
    | '/pms/pos/settings/general'
    | '/pms/pos/settings/payment-tax'
    | '/pms/pos/settings/printers'
    | '/pms/pos/settings/stations'
    | '/pms/pos/settings/store'
    | '/pms/pos/settings/table-groups'
    | '/pms/pos/settings/utility'
    | '/pms/pos/manage'
    | '/pms/pos/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking-success'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/pms'
    | '/portal'
    | '/privacy'
    | '/signup'
    | '/stays'
    | '/terms'
    | '/admin_/bookings'
    | '/blog/$slug'
    | '/locations/$slug'
    | '/pms/airbnb-spaces'
    | '/pms/bookings'
    | '/pms/caretaker'
    | '/pms/expenses'
    | '/pms/inquiries'
    | '/pms/inventory'
    | '/pms/invoices'
    | '/pms/pos'
    | '/pms/settings'
    | '/pms/super-admin'
    | '/pms/system'
    | '/pms/vouchers'
    | '/pms_/login'
    | '/pms_/onboarding'
    | '/portal/dashboard'
    | '/portal/login'
    | '/properties/$slug'
    | '/stays_/large-groups'
    | '/stays_/private-pool-villas'
    | '/blog/'
    | '/pms/'
    | '/portal/'
    | '/pms/invoices_/new'
    | '/pms/pos/help'
    | '/pms/pos/manage'
    | '/pms/pos/orders'
    | '/pms/pos/quick'
    | '/pms/pos/reports'
    | '/pms/pos/settings'
    | '/pms/settings_/users'
    | '/pms_/auth/callback'
    | '/pms_/auth/google-start'
    | '/pms/pos/'
    | '/pms/pos/manage/activity-logs'
    | '/pms/pos/manage/categories'
    | '/pms/pos/manage/customers'
    | '/pms/pos/manage/employees'
    | '/pms/pos/manage/income-expense'
    | '/pms/pos/manage/invoices'
    | '/pms/pos/manage/items'
    | '/pms/pos/settings/discounts'
    | '/pms/pos/settings/display'
    | '/pms/pos/settings/general'
    | '/pms/pos/settings/payment-tax'
    | '/pms/pos/settings/printers'
    | '/pms/pos/settings/stations'
    | '/pms/pos/settings/store'
    | '/pms/pos/settings/table-groups'
    | '/pms/pos/settings/utility'
    | '/pms/pos/manage/'
    | '/pms/pos/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PmsRoute: typeof PmsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  StaysRoute: typeof StaysRoute
  TermsRoute: typeof TermsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PmsLoginRoute: typeof PmsLoginRoute
  PmsOnboardingRoute: typeof PmsOnboardingRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  StaysLargeGroupsRoute: typeof StaysLargeGroupsRoute
  StaysPrivatePoolVillasRoute: typeof StaysPrivatePoolVillasRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PmsAuthCallbackRoute: typeof PmsAuthCallbackRoute
  PmsAuthGoogleStartRoute: typeof PmsAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms': {
      id: '/pms'
      path: '/pms'
      fullPath: '/pms'
      preLoaderRoute: typeof PmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/bookings': {
      id: '/admin_/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/': {
      id: '/pms/'
      path: '/'
      fullPath: '/pms/'
      preLoaderRoute: typeof PmsIndexRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/airbnb-spaces': {
      id: '/pms/airbnb-spaces'
      path: '/airbnb-spaces'
      fullPath: '/pms/airbnb-spaces'
      preLoaderRoute: typeof PmsAirbnbSpacesRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/bookings': {
      id: '/pms/bookings'
      path: '/bookings'
      fullPath: '/pms/bookings'
      preLoaderRoute: typeof PmsBookingsRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/caretaker': {
      id: '/pms/caretaker'
      path: '/caretaker'
      fullPath: '/pms/caretaker'
      preLoaderRoute: typeof PmsCaretakerRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/expenses': {
      id: '/pms/expenses'
      path: '/expenses'
      fullPath: '/pms/expenses'
      preLoaderRoute: typeof PmsExpensesRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/inquiries': {
      id: '/pms/inquiries'
      path: '/inquiries'
      fullPath: '/pms/inquiries'
      preLoaderRoute: typeof PmsInquiriesRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/inventory': {
      id: '/pms/inventory'
      path: '/inventory'
      fullPath: '/pms/inventory'
      preLoaderRoute: typeof PmsInventoryRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/invoices': {
      id: '/pms/invoices'
      path: '/invoices'
      fullPath: '/pms/invoices'
      preLoaderRoute: typeof PmsInvoicesRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/pos': {
      id: '/pms/pos'
      path: '/pos'
      fullPath: '/pms/pos'
      preLoaderRoute: typeof PmsPosRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/settings': {
      id: '/pms/settings'
      path: '/settings'
      fullPath: '/pms/settings'
      preLoaderRoute: typeof PmsSettingsRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/super-admin': {
      id: '/pms/super-admin'
      path: '/super-admin'
      fullPath: '/pms/super-admin'
      preLoaderRoute: typeof PmsSuperAdminRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/system': {
      id: '/pms/system'
      path: '/system'
      fullPath: '/pms/system'
      preLoaderRoute: typeof PmsSystemRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/vouchers': {
      id: '/pms/vouchers'
      path: '/vouchers'
      fullPath: '/pms/vouchers'
      preLoaderRoute: typeof PmsVouchersRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms_/login': {
      id: '/pms_/login'
      path: '/pms/login'
      fullPath: '/pms/login'
      preLoaderRoute: typeof PmsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms_/onboarding': {
      id: '/pms_/onboarding'
      path: '/pms/onboarding'
      fullPath: '/pms/onboarding'
      preLoaderRoute: typeof PmsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays_/large-groups': {
      id: '/stays_/large-groups'
      path: '/stays/large-groups'
      fullPath: '/stays/large-groups'
      preLoaderRoute: typeof StaysLargeGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays_/private-pool-villas': {
      id: '/stays_/private-pool-villas'
      path: '/stays/private-pool-villas'
      fullPath: '/stays/private-pool-villas'
      preLoaderRoute: typeof StaysPrivatePoolVillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/invoices_/new': {
      id: '/pms/invoices_/new'
      path: '/invoices/new'
      fullPath: '/pms/invoices/new'
      preLoaderRoute: typeof PmsInvoicesNewRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/pos/': {
      id: '/pms/pos/'
      path: '/'
      fullPath: '/pms/pos/'
      preLoaderRoute: typeof PmsPosIndexRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/pos/help': {
      id: '/pms/pos/help'
      path: '/help'
      fullPath: '/pms/pos/help'
      preLoaderRoute: typeof PmsPosHelpRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/pos/manage': {
      id: '/pms/pos/manage'
      path: '/manage'
      fullPath: '/pms/pos/manage'
      preLoaderRoute: typeof PmsPosManageRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/pos/orders': {
      id: '/pms/pos/orders'
      path: '/orders'
      fullPath: '/pms/pos/orders'
      preLoaderRoute: typeof PmsPosOrdersRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/pos/quick': {
      id: '/pms/pos/quick'
      path: '/quick'
      fullPath: '/pms/pos/quick'
      preLoaderRoute: typeof PmsPosQuickRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/pos/reports': {
      id: '/pms/pos/reports'
      path: '/reports'
      fullPath: '/pms/pos/reports'
      preLoaderRoute: typeof PmsPosReportsRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/pos/settings': {
      id: '/pms/pos/settings'
      path: '/settings'
      fullPath: '/pms/pos/settings'
      preLoaderRoute: typeof PmsPosSettingsRouteImport
      parentRoute: typeof PmsPosRoute
    }
    '/pms/settings_/users': {
      id: '/pms/settings_/users'
      path: '/settings/users'
      fullPath: '/pms/settings/users'
      preLoaderRoute: typeof PmsSettingsUsersRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms_/auth/callback': {
      id: '/pms_/auth/callback'
      path: '/pms/auth/callback'
      fullPath: '/pms/auth/callback'
      preLoaderRoute: typeof PmsAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms_/auth/google-start': {
      id: '/pms_/auth/google-start'
      path: '/pms/auth/google-start'
      fullPath: '/pms/auth/google-start'
      preLoaderRoute: typeof PmsAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/pos/manage/': {
      id: '/pms/pos/manage/'
      path: '/'
      fullPath: '/pms/pos/manage/'
      preLoaderRoute: typeof PmsPosManageIndexRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/activity-logs': {
      id: '/pms/pos/manage/activity-logs'
      path: '/activity-logs'
      fullPath: '/pms/pos/manage/activity-logs'
      preLoaderRoute: typeof PmsPosManageActivityLogsRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/categories': {
      id: '/pms/pos/manage/categories'
      path: '/categories'
      fullPath: '/pms/pos/manage/categories'
      preLoaderRoute: typeof PmsPosManageCategoriesRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/customers': {
      id: '/pms/pos/manage/customers'
      path: '/customers'
      fullPath: '/pms/pos/manage/customers'
      preLoaderRoute: typeof PmsPosManageCustomersRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/employees': {
      id: '/pms/pos/manage/employees'
      path: '/employees'
      fullPath: '/pms/pos/manage/employees'
      preLoaderRoute: typeof PmsPosManageEmployeesRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/income-expense': {
      id: '/pms/pos/manage/income-expense'
      path: '/income-expense'
      fullPath: '/pms/pos/manage/income-expense'
      preLoaderRoute: typeof PmsPosManageIncomeExpenseRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/invoices': {
      id: '/pms/pos/manage/invoices'
      path: '/invoices'
      fullPath: '/pms/pos/manage/invoices'
      preLoaderRoute: typeof PmsPosManageInvoicesRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/manage/items': {
      id: '/pms/pos/manage/items'
      path: '/items'
      fullPath: '/pms/pos/manage/items'
      preLoaderRoute: typeof PmsPosManageItemsRouteImport
      parentRoute: typeof PmsPosManageRoute
    }
    '/pms/pos/settings/': {
      id: '/pms/pos/settings/'
      path: '/'
      fullPath: '/pms/pos/settings/'
      preLoaderRoute: typeof PmsPosSettingsIndexRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/discounts': {
      id: '/pms/pos/settings/discounts'
      path: '/discounts'
      fullPath: '/pms/pos/settings/discounts'
      preLoaderRoute: typeof PmsPosSettingsDiscountsRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/display': {
      id: '/pms/pos/settings/display'
      path: '/display'
      fullPath: '/pms/pos/settings/display'
      preLoaderRoute: typeof PmsPosSettingsDisplayRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/general': {
      id: '/pms/pos/settings/general'
      path: '/general'
      fullPath: '/pms/pos/settings/general'
      preLoaderRoute: typeof PmsPosSettingsGeneralRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/payment-tax': {
      id: '/pms/pos/settings/payment-tax'
      path: '/payment-tax'
      fullPath: '/pms/pos/settings/payment-tax'
      preLoaderRoute: typeof PmsPosSettingsPaymentTaxRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/printers': {
      id: '/pms/pos/settings/printers'
      path: '/printers'
      fullPath: '/pms/pos/settings/printers'
      preLoaderRoute: typeof PmsPosSettingsPrintersRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/stations': {
      id: '/pms/pos/settings/stations'
      path: '/stations'
      fullPath: '/pms/pos/settings/stations'
      preLoaderRoute: typeof PmsPosSettingsStationsRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/store': {
      id: '/pms/pos/settings/store'
      path: '/store'
      fullPath: '/pms/pos/settings/store'
      preLoaderRoute: typeof PmsPosSettingsStoreRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/table-groups': {
      id: '/pms/pos/settings/table-groups'
      path: '/table-groups'
      fullPath: '/pms/pos/settings/table-groups'
      preLoaderRoute: typeof PmsPosSettingsTableGroupsRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
    '/pms/pos/settings/utility': {
      id: '/pms/pos/settings/utility'
      path: '/utility'
      fullPath: '/pms/pos/settings/utility'
      preLoaderRoute: typeof PmsPosSettingsUtilityRouteImport
      parentRoute: typeof PmsPosSettingsRoute
    }
  }
}

interface PmsPosManageRouteChildren {
  PmsPosManageActivityLogsRoute: typeof PmsPosManageActivityLogsRoute
  PmsPosManageCategoriesRoute: typeof PmsPosManageCategoriesRoute
  PmsPosManageCustomersRoute: typeof PmsPosManageCustomersRoute
  PmsPosManageEmployeesRoute: typeof PmsPosManageEmployeesRoute
  PmsPosManageIncomeExpenseRoute: typeof PmsPosManageIncomeExpenseRoute
  PmsPosManageInvoicesRoute: typeof PmsPosManageInvoicesRoute
  PmsPosManageItemsRoute: typeof PmsPosManageItemsRoute
  PmsPosManageIndexRoute: typeof PmsPosManageIndexRoute
}

const PmsPosManageRouteChildren: PmsPosManageRouteChildren = {
  PmsPosManageActivityLogsRoute: PmsPosManageActivityLogsRoute,
  PmsPosManageCategoriesRoute: PmsPosManageCategoriesRoute,
  PmsPosManageCustomersRoute: PmsPosManageCustomersRoute,
  PmsPosManageEmployeesRoute: PmsPosManageEmployeesRoute,
  PmsPosManageIncomeExpenseRoute: PmsPosManageIncomeExpenseRoute,
  PmsPosManageInvoicesRoute: PmsPosManageInvoicesRoute,
  PmsPosManageItemsRoute: PmsPosManageItemsRoute,
  PmsPosManageIndexRoute: PmsPosManageIndexRoute,
}

const PmsPosManageRouteWithChildren = PmsPosManageRoute._addFileChildren(
  PmsPosManageRouteChildren,
)

interface PmsPosSettingsRouteChildren {
  PmsPosSettingsDiscountsRoute: typeof PmsPosSettingsDiscountsRoute
  PmsPosSettingsDisplayRoute: typeof PmsPosSettingsDisplayRoute
  PmsPosSettingsGeneralRoute: typeof PmsPosSettingsGeneralRoute
  PmsPosSettingsPaymentTaxRoute: typeof PmsPosSettingsPaymentTaxRoute
  PmsPosSettingsPrintersRoute: typeof PmsPosSettingsPrintersRoute
  PmsPosSettingsStationsRoute: typeof PmsPosSettingsStationsRoute
  PmsPosSettingsStoreRoute: typeof PmsPosSettingsStoreRoute
  PmsPosSettingsTableGroupsRoute: typeof PmsPosSettingsTableGroupsRoute
  PmsPosSettingsUtilityRoute: typeof PmsPosSettingsUtilityRoute
  PmsPosSettingsIndexRoute: typeof PmsPosSettingsIndexRoute
}

const PmsPosSettingsRouteChildren: PmsPosSettingsRouteChildren = {
  PmsPosSettingsDiscountsRoute: PmsPosSettingsDiscountsRoute,
  PmsPosSettingsDisplayRoute: PmsPosSettingsDisplayRoute,
  PmsPosSettingsGeneralRoute: PmsPosSettingsGeneralRoute,
  PmsPosSettingsPaymentTaxRoute: PmsPosSettingsPaymentTaxRoute,
  PmsPosSettingsPrintersRoute: PmsPosSettingsPrintersRoute,
  PmsPosSettingsStationsRoute: PmsPosSettingsStationsRoute,
  PmsPosSettingsStoreRoute: PmsPosSettingsStoreRoute,
  PmsPosSettingsTableGroupsRoute: PmsPosSettingsTableGroupsRoute,
  PmsPosSettingsUtilityRoute: PmsPosSettingsUtilityRoute,
  PmsPosSettingsIndexRoute: PmsPosSettingsIndexRoute,
}

const PmsPosSettingsRouteWithChildren = PmsPosSettingsRoute._addFileChildren(
  PmsPosSettingsRouteChildren,
)

interface PmsPosRouteChildren {
  PmsPosHelpRoute: typeof PmsPosHelpRoute
  PmsPosManageRoute: typeof PmsPosManageRouteWithChildren
  PmsPosOrdersRoute: typeof PmsPosOrdersRoute
  PmsPosQuickRoute: typeof PmsPosQuickRoute
  PmsPosReportsRoute: typeof PmsPosReportsRoute
  PmsPosSettingsRoute: typeof PmsPosSettingsRouteWithChildren
  PmsPosIndexRoute: typeof PmsPosIndexRoute
}

const PmsPosRouteChildren: PmsPosRouteChildren = {
  PmsPosHelpRoute: PmsPosHelpRoute,
  PmsPosManageRoute: PmsPosManageRouteWithChildren,
  PmsPosOrdersRoute: PmsPosOrdersRoute,
  PmsPosQuickRoute: PmsPosQuickRoute,
  PmsPosReportsRoute: PmsPosReportsRoute,
  PmsPosSettingsRoute: PmsPosSettingsRouteWithChildren,
  PmsPosIndexRoute: PmsPosIndexRoute,
}

const PmsPosRouteWithChildren =
  PmsPosRoute._addFileChildren(PmsPosRouteChildren)

interface PmsRouteChildren {
  PmsAirbnbSpacesRoute: typeof PmsAirbnbSpacesRoute
  PmsBookingsRoute: typeof PmsBookingsRoute
  PmsCaretakerRoute: typeof PmsCaretakerRoute
  PmsExpensesRoute: typeof PmsExpensesRoute
  PmsInquiriesRoute: typeof PmsInquiriesRoute
  PmsInventoryRoute: typeof PmsInventoryRoute
  PmsInvoicesRoute: typeof PmsInvoicesRoute
  PmsPosRoute: typeof PmsPosRouteWithChildren
  PmsSettingsRoute: typeof PmsSettingsRoute
  PmsSuperAdminRoute: typeof PmsSuperAdminRoute
  PmsSystemRoute: typeof PmsSystemRoute
  PmsVouchersRoute: typeof PmsVouchersRoute
  PmsIndexRoute: typeof PmsIndexRoute
  PmsInvoicesNewRoute: typeof PmsInvoicesNewRoute
  PmsSettingsUsersRoute: typeof PmsSettingsUsersRoute
}

const PmsRouteChildren: PmsRouteChildren = {
  PmsAirbnbSpacesRoute: PmsAirbnbSpacesRoute,
  PmsBookingsRoute: PmsBookingsRoute,
  PmsCaretakerRoute: PmsCaretakerRoute,
  PmsExpensesRoute: PmsExpensesRoute,
  PmsInquiriesRoute: PmsInquiriesRoute,
  PmsInventoryRoute: PmsInventoryRoute,
  PmsInvoicesRoute: PmsInvoicesRoute,
  PmsPosRoute: PmsPosRouteWithChildren,
  PmsSettingsRoute: PmsSettingsRoute,
  PmsSuperAdminRoute: PmsSuperAdminRoute,
  PmsSystemRoute: PmsSystemRoute,
  PmsVouchersRoute: PmsVouchersRoute,
  PmsIndexRoute: PmsIndexRoute,
  PmsInvoicesNewRoute: PmsInvoicesNewRoute,
  PmsSettingsUsersRoute: PmsSettingsUsersRoute,
}

const PmsRouteWithChildren = PmsRoute._addFileChildren(PmsRouteChildren)

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PmsRoute: PmsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  StaysRoute: StaysRoute,
  TermsRoute: TermsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PmsLoginRoute: PmsLoginRoute,
  PmsOnboardingRoute: PmsOnboardingRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  StaysLargeGroupsRoute: StaysLargeGroupsRoute,
  StaysPrivatePoolVillasRoute: StaysPrivatePoolVillasRoute,
  BlogIndexRoute: BlogIndexRoute,
  PmsAuthCallbackRoute: PmsAuthCallbackRoute,
  PmsAuthGoogleStartRoute: PmsAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
