/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PmsRouteImport } from './routes/pms'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminBookingsRouteImport } from './routes/admin_.bookings'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as PmsIndexRouteImport } from './routes/pms.index'
import { Route as PmsBookingsRouteImport } from './routes/pms.bookings'
import { Route as PmsExpensesRouteImport } from './routes/pms.expenses'
import { Route as PmsInventoryRouteImport } from './routes/pms.inventory'
import { Route as PmsInvoicesRouteImport } from './routes/pms.invoices'
import { Route as PmsSystemRouteImport } from './routes/pms.system'
import { Route as PmsLoginRouteImport } from './routes/pms_.login'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as StaysLargeGroupsRouteImport } from './routes/stays_.large-groups'
import { Route as StaysPrivatePoolVillasRouteImport } from './routes/stays_.private-pool-villas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsRoute = PmsRouteImport.update({
  id: '/pms',
  path: '/pms',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin_/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsIndexRoute = PmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmsRoute,
} as any)
const PmsBookingsRoute = PmsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PmsRoute,
} as any)
const PmsExpensesRoute = PmsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => PmsRoute,
} as any)
const PmsInventoryRoute = PmsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PmsRoute,
} as any)
const PmsInvoicesRoute = PmsInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PmsRoute,
} as any)
const PmsSystemRoute = PmsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => PmsRoute,
} as any)
const PmsLoginRoute = PmsLoginRouteImport.update({
  id: '/pms_/login',
  path: '/pms/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysLargeGroupsRoute = StaysLargeGroupsRouteImport.update({
  id: '/stays_/large-groups',
  path: '/stays/large-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysPrivatePoolVillasRoute = StaysPrivatePoolVillasRouteImport.update({
  id: '/stays_/private-pool-villas',
  path: '/stays/private-pool-villas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pms': typeof PmsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/stays': typeof StaysRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/pms/bookings': typeof PmsBookingsRoute
  '/pms/expenses': typeof PmsExpensesRoute
  '/pms/inventory': typeof PmsInventoryRoute
  '/pms/invoices': typeof PmsInvoicesRoute
  '/pms/system': typeof PmsSystemRoute
  '/pms/login': typeof PmsLoginRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/stays/large-groups': typeof StaysLargeGroupsRoute
  '/stays/private-pool-villas': typeof StaysPrivatePoolVillasRoute
  '/blog/': typeof BlogIndexRoute
  '/pms/': typeof PmsIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/stays': typeof StaysRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/pms/bookings': typeof PmsBookingsRoute
  '/pms/expenses': typeof PmsExpensesRoute
  '/pms/inventory': typeof PmsInventoryRoute
  '/pms/invoices': typeof PmsInvoicesRoute
  '/pms/system': typeof PmsSystemRoute
  '/pms/login': typeof PmsLoginRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/stays/large-groups': typeof StaysLargeGroupsRoute
  '/stays/private-pool-villas': typeof StaysPrivatePoolVillasRoute
  '/blog': typeof BlogIndexRoute
  '/pms': typeof PmsIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pms': typeof PmsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/stays': typeof StaysRoute
  '/terms': typeof TermsRoute
  '/admin_/bookings': typeof AdminBookingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/pms/bookings': typeof PmsBookingsRoute
  '/pms/expenses': typeof PmsExpensesRoute
  '/pms/inventory': typeof PmsInventoryRoute
  '/pms/invoices': typeof PmsInvoicesRoute
  '/pms/system': typeof PmsSystemRoute
  '/pms_/login': typeof PmsLoginRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/stays_/large-groups': typeof StaysLargeGroupsRoute
  '/stays_/private-pool-villas': typeof StaysPrivatePoolVillasRoute
  '/blog/': typeof BlogIndexRoute
  '/pms/': typeof PmsIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking-success'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/pms'
    | '/portal'
    | '/privacy'
    | '/stays'
    | '/terms'
    | '/admin/bookings'
    | '/blog/$slug'
    | '/locations/$slug'
    | '/pms/bookings'
    | '/pms/expenses'
    | '/pms/inventory'
    | '/pms/invoices'
    | '/pms/system'
    | '/pms/login'
    | '/portal/dashboard'
    | '/portal/login'
    | '/properties/$slug'
    | '/stays/large-groups'
    | '/stays/private-pool-villas'
    | '/blog/'
    | '/pms/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking-success'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/stays'
    | '/terms'
    | '/admin/bookings'
    | '/blog/$slug'
    | '/locations/$slug'
    | '/pms/bookings'
    | '/pms/expenses'
    | '/pms/inventory'
    | '/pms/invoices'
    | '/pms/system'
    | '/pms/login'
    | '/portal/dashboard'
    | '/portal/login'
    | '/properties/$slug'
    | '/stays/large-groups'
    | '/stays/private-pool-villas'
    | '/blog'
    | '/pms'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking-success'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/pms'
    | '/portal'
    | '/privacy'
    | '/stays'
    | '/terms'
    | '/admin_/bookings'
    | '/blog/$slug'
    | '/locations/$slug'
    | '/pms/bookings'
    | '/pms/expenses'
    | '/pms/inventory'
    | '/pms/invoices'
    | '/pms/system'
    | '/pms_/login'
    | '/portal/dashboard'
    | '/portal/login'
    | '/properties/$slug'
    | '/stays_/large-groups'
    | '/stays_/private-pool-villas'
    | '/blog/'
    | '/pms/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PmsRoute: typeof PmsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  StaysRoute: typeof StaysRoute
  TermsRoute: typeof TermsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PmsLoginRoute: typeof PmsLoginRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  StaysLargeGroupsRoute: typeof StaysLargeGroupsRoute
  StaysPrivatePoolVillasRoute: typeof StaysPrivatePoolVillasRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms': {
      id: '/pms'
      path: '/pms'
      fullPath: '/pms'
      preLoaderRoute: typeof PmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/bookings': {
      id: '/admin_/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/': {
      id: '/pms/'
      path: '/'
      fullPath: '/pms/'
      preLoaderRoute: typeof PmsIndexRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/bookings': {
      id: '/pms/bookings'
      path: '/bookings'
      fullPath: '/pms/bookings'
      preLoaderRoute: typeof PmsBookingsRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/expenses': {
      id: '/pms/expenses'
      path: '/expenses'
      fullPath: '/pms/expenses'
      preLoaderRoute: typeof PmsExpensesRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/inventory': {
      id: '/pms/inventory'
      path: '/inventory'
      fullPath: '/pms/inventory'
      preLoaderRoute: typeof PmsInventoryRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/invoices': {
      id: '/pms/invoices'
      path: '/invoices'
      fullPath: '/pms/invoices'
      preLoaderRoute: typeof PmsInvoicesRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms/system': {
      id: '/pms/system'
      path: '/system'
      fullPath: '/pms/system'
      preLoaderRoute: typeof PmsSystemRouteImport
      parentRoute: typeof PmsRoute
    }
    '/pms_/login': {
      id: '/pms_/login'
      path: '/pms/login'
      fullPath: '/pms/login'
      preLoaderRoute: typeof PmsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays_/large-groups': {
      id: '/stays_/large-groups'
      path: '/stays/large-groups'
      fullPath: '/stays/large-groups'
      preLoaderRoute: typeof StaysLargeGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays_/private-pool-villas': {
      id: '/stays_/private-pool-villas'
      path: '/stays/private-pool-villas'
      fullPath: '/stays/private-pool-villas'
      preLoaderRoute: typeof StaysPrivatePoolVillasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PmsRouteChildren {
  PmsBookingsRoute: typeof PmsBookingsRoute
  PmsExpensesRoute: typeof PmsExpensesRoute
  PmsInventoryRoute: typeof PmsInventoryRoute
  PmsInvoicesRoute: typeof PmsInvoicesRoute
  PmsSystemRoute: typeof PmsSystemRoute
  PmsIndexRoute: typeof PmsIndexRoute
}

const PmsRouteChildren: PmsRouteChildren = {
  PmsBookingsRoute: PmsBookingsRoute,
  PmsExpensesRoute: PmsExpensesRoute,
  PmsInventoryRoute: PmsInventoryRoute,
  PmsInvoicesRoute: PmsInvoicesRoute,
  PmsSystemRoute: PmsSystemRoute,
  PmsIndexRoute: PmsIndexRoute,
}

const PmsRouteWithChildren = PmsRoute._addFileChildren(PmsRouteChildren)

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PmsRoute: PmsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  StaysRoute: StaysRoute,
  TermsRoute: TermsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PmsLoginRoute: PmsLoginRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  StaysLargeGroupsRoute: StaysLargeGroupsRoute,
  StaysPrivatePoolVillasRoute: StaysPrivatePoolVillasRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
