// One extra, link-free paragraph per section (posts 2-30) — practical depth
// that brings each post into the 500-700 word range without adding links or
// new factual claims about the properties. Post 1 already clears the floor.
export const extras: Record<number, [string, string]> = {
  2: [
    "Think about how the day actually runs. Early risers want coffee on the terrace, teenagers want a pool that feels theirs after dark, and grandparents want a comfortable chair in the shade. A layout with a ground-floor bedroom, a shaded seating area and a second sitting space lets everyone spread out without feeling isolated. It also pays to ask how bedrooms are arranged: adjoining rooms suit parents with young children, while a separate wing is ideal for older relatives who turn in early.",
    "Whichever size you choose, decide who is responsible for what before you arrive. Nominate one person to handle the booking, another to plan meals, and share the house rules with the whole group so nobody is surprised by the 10:00 PM music limit or the rules on extra guests. A short shared checklist saves a surprising number of arguments, and it leaves more time for the pool.",
  ],
  3: [
    "If you are travelling in October, plan around the weather rather than fighting it. Mornings are usually the clearest, so save beach time for the early hours and keep afternoons for the pool, a long lunch or a market visit. Showers tend to be short and heavy rather than all-day, so a flexible plan works better than a fixed itinerary, and the reward is beaches that feel almost private compared with peak season.",
    "Once shacks open, the etiquette is simple: order something before you claim a lounger, keep your belongings close, and settle the bill clearly before you leave. Prices for loungers and food are usually posted or can be asked for, so do not be shy about checking. If a shack is not yet open, staff at neighbouring ones are usually happy to point you to somewhere that is, which makes early season friendlier than you might expect.",
  ],
  4: [
    "Think of the chef as part of the holiday plan rather than a last-minute extra. Decide which meals matter most to you — a slow first-night dinner, a relaxed poolside lunch or a big family breakfast — and book those first. Sharing the group's size, ages and favourite cuisines when you request the service lets the chef shop and prepare properly, and it avoids the classic problem of cooking far too much or too little.",
    "Most groups find that a mix works best: one or two chef-cooked meals that feel special, and the rest eating out or cooking simply. That keeps costs sensible and still gives you the memorable dinners. Ask your caretaker how the kitchen is set up and agree the timings. The evening should wind down by the 10:00 PM noise limit, which makes early dinners the most relaxed option for families.",
  ],
  5: [
    "Neighbours are the reason these rules exist, and a little goodwill goes a long way. Introduce yourself to your caretaker, ask whether anything nearby is sensitive — an elderly neighbour, a newborn, an exam period — and adjust accordingly. Most complaints come not from noise itself but from surprise, so setting expectations early with your group matters, especially if guests arrive late or leave loudly after a night out.",
    "For pet owners, the difference between a good and a stressful stay is preparation. Bring your pet's own bedding, keep to its usual feeding routine and plan quiet time in the heat of the day, since Goa is warm even in the cooler months. Tell your caretaker about any allergies, fears or habits, such as barking at strangers, so housekeeping and maintenance visits can be scheduled around your pet rather than disturbing it.",
  ],
  6: [
    "If you are flying in for the weekend, keep the plan light. Land, settle in, swim and eat well on day one, and resist the urge to cram every attraction into the remaining days. Short trips feel best when there is a rhythm: a slow morning, one outing, a long lunch and a quiet evening. That is how a villa turns a four-day break into something that feels like a proper holiday rather than a sprint.",
    "Since Dussehra is a festival, expect some local celebrations and busier roads around the day itself. Leave a little extra time for airport transfers, and ask your caretaker about anything happening nearby if you would like to watch. Cultural events are a good way to add a memorable evening without much planning, and the villa gives you a calm base to retreat to afterwards, with your own pool waiting when you return.",
  ],
  7: [
    "Photographers should plan the golden hour carefully. The stone walls glow warm in low light, and the river mouth and headland create natural leading lines, so a wide lens works well. If you would rather be in the moment than behind a lens, take a few frames early and then put the phone away. Sunsets in Goa often keep improving for ten or fifteen minutes after the sun dips, so stay a little longer than seems necessary.",
    "A relaxed way to build a route is to pair a viewpoint with a meal. Watch the light from the fort or a cliff, then head to dinner while the sky is still colouring, rather than rushing back to the car park with everyone else. Traffic on the narrow roads around Vagator can slow noticeably at dusk, so building in a buffer, or leaving just before the crowd, makes the evening feel effortless.",
  ],
  8: [
    "With big groups, the small decisions add up. Decide early who is arriving when, since staggered arrivals need clear check-in instructions, and confirm how many rooms are needed for families versus friends sharing. A group photo on the beach on the first afternoon is worth planning, because it is much harder to gather fifty people once the trip is under way. Share a simple schedule so everyone knows the plan without a hundred messages.",
    "Food is usually the biggest variable for large groups, so agree dietary needs and meal timings ahead of arrival. Where a property has its own restaurant, that can simplify catering considerably, and you can build the group's meals around a few shared sit-down occasions. Keep an eye on children's meals, vegetarian and vegan requirements and any allergies, and give the kitchen as much notice as you can, since cooking for a crowd takes preparation.",
  ],
  9: [
    "Another thing that separates a villa is the pace. There are no set breakfast hours, no towels to reserve and no queue for the pool. Your day starts when you do, and the household adapts. For many travellers, particularly families with children or groups of friends on different schedules, that flexibility is the biggest luxury of all, and it is hard to replicate in a property designed to run on timetables.",
    "Think honestly about what you will actually use. If you will spend most of the trip out exploring, a resort's spa and gym may go unvisited, while a villa's kitchen and pool would be used daily. If you love being looked after with no decisions to make, a resort may suit you better. Matching the stay to how you really travel is the most reliable way to avoid disappointment and to feel you got good value.",
  ],
  10: [
    "If you prefer a quieter evening, Anjuna has plenty of options that are more about atmosphere than volume: garden restaurants, cafes that stay open late and beach bars where conversation still carries. The trick is to pick the mood first and the venue second. Ask your caretaker what is on that particular night, since listings, live music nights and themed evenings change often and are rarely updated online, and the best plans usually come from local word of mouth.",
    "Safety and comfort are simple with a little forethought. Agree a meeting point with your group, keep phones charged and share the villa's address with everyone. Carry some cash, avoid leaving drinks unattended and let someone know if you are heading elsewhere. Sensible habits keep the night relaxed, and a private pool waiting back at the villa makes the end of the night one of the best parts of it. Hydrate, eat well and pace yourself.",
  ],
  11: [
    "Bring a reusable water bottle and a light scarf or hat, and dress modestly if you plan to step into any of the village's small chapels or shrines. Wandering without a fixed destination is the best method: turn down any lane that looks inviting and you will usually find a courtyard, a mural or a tiny shop. Keep to the road edges and give way to scooters, which appear quickly around the bends.",
    "If you want to shop, be curious and ask about the maker. Many boutique owners are happy to explain how an item was made, and buying directly supports independent craft. Keep some space in your bag and check delivery options if you find something large. A slow afternoon of browsing, coffee and cake that ends with a swim back at the villa is the ideal pace for Assagao.",
  ],
  12: [
    "Design the days around energy, not just content. Put the hardest conversations in the morning when people are sharpest, keep afternoons flexible for walks or one-to-one talks, and leave evenings for meals and informal time. Executives often say the best decisions of a retreat come out of the unstructured moments, so protect them. A villa setting makes that natural, because there is no lobby to cross and no schedule imposed by the venue.",
    "Logistics decide whether a retreat feels smooth or stressful. Confirm arrival times, agree who is arranging transfers and share dietary needs with the chef in advance. Ask about spaces for private calls, since senior teams rarely go fully offline, and agree quiet hours. Finally, keep the budget clear: a per-person view of accommodation, food and transport helps leadership see the real cost and avoids surprises when the final invoice arrives.",
  ],
  13: [
    "When you are choosing between cafes, watch what the kitchen does with simple things. Good eggs, properly baked bread and fresh fruit tell you more than a long menu of trendy dishes. If a place makes its own granola, chutneys or nut butters, that is usually a good sign. Locals tend to know the best spots, so ask your caretaker or a friendly shopkeeper where they eat breakfast rather than relying only on online lists.",
    "A market run makes a great morning activity. Pick up fresh fruit, eggs, bread and a few local specialities, then cook a slow breakfast with the group. It is cheaper than eating out every day, lets you control ingredients for dietary needs and gives children something to do. Keep a few staples such as coffee, honey and yoghurt in the kitchen so a good breakfast is always within reach.",
  ],
  14: [
    "Keep a record of everything. Note the taxi's number plate, screenshot your booking or message, and save the driver's phone number. If a dispute arises, having those details makes it far easier to resolve, whether with your villa or with the local authorities. Most drivers are honest, and a calm, friendly approach works better than confrontation, but a paper trail protects you in the rare cases where it matters.",
    "If you choose to drive yourself, remember that roads in Goa can be narrow, unlit and busy with scooters, animals and pedestrians. Drive slowly, avoid unfamiliar routes after dark and never drink and drive. Parking at popular beaches can be tricky, so allow extra time. For many visitors, hiring a driver for longer days is not just safer but also more relaxing, leaving everyone free to enjoy the scenery.",
  ],
  15: [
    "It helps to compare per person rather than per room. Divide the total for each option by the number of guests and nights, then add what you would realistically spend on food, transfers and activities. A hotel's dining and transport costs can be significant, while a villa lets you cook, share and split costs. The per-person number is often the fairest way to see which option really works for your group.",
    "Also weigh the things a spreadsheet misses: privacy, space, flexibility and how well the trip fits your group. Some people value the convenience of a hotel, others the feeling of a home. There is no universal winner, only a better match for your priorities and budget. Ask for written quotes for both and include every fee, so the decision rests on real numbers instead of guesses.",
  ],
  16: [
    "Hatchlings typically emerge at night and head towards the brightest horizon, which should be the sea. Artificial lights, such as floodlights or phone torches, can lead them the wrong way, so keep outdoor lighting dim and shielded near the beach where you can. Keeping the sand clear of holes, beach chairs and litter also helps, because obstacles can trap or exhaust tiny hatchlings on their journey to the water.",
    "Responsible tourism goes beyond the turtles. Choose businesses that follow local rules, avoid single-use plastics, respect quiet hours and keep noise low near nesting areas. If you spot a nest, a stranded turtle or an unusual disturbance, report it to the local authorities or conservation team rather than acting alone. Small, considerate choices from many visitors are what allow this coast to remain a home for wildlife.",
  ],
  17: [
    "A heritage stay is also about how you use the space. Eat on the veranda, read in the shade and let the afternoon slow down, because the design invites exactly that. Guests often find that the house shapes the holiday: mealtimes stretch, children play on the lawn and conversation drifts. If you want a trip that feels less like a hotel stay and more like a family house party, this is the format, and it suits multi-generational groups well.",
    "Candolim also makes an easy base for exploring the wider coast. Beaches, restaurants and water sports are close, and the fort offers a lovely view at the end of the day. Plan a mix of activities and slow days at the bungalow, and take advantage of the lawn for evening games. With rooms bookable individually, families and friends can travel together yet still enjoy their own space.",
  ],
  18: [
    "Routines matter more than itineraries with little ones. Try to keep naps and mealtimes roughly as they are at home, and plan outings around them. Pack familiar snacks, a favourite toy and any comfort items, and choose activities that suit a toddler's energy, such as short beach visits in the cooler hours. A calm base like a villa makes it much easier to stick to a routine than a busy resort would.",
    "Health basics are worth a little thought. Bring sunscreen suitable for children, insect repellent and a simple first-aid kit, and encourage plenty of clean water. If your child falls ill, your caretaker can help you find a local clinic or doctor. Check that vaccinations are up to date before you travel, and speak to your paediatrician if you have any concerns about the climate, food or activities.",
  ],
  19: [
    "Pacing is everything on a circuit night. Start with water as well as cocktails, eat properly before the music starts and avoid rushing between venues. Agree a rough plan with your group, including a time you might head home, and share live locations so nobody gets left behind. Late nights are more enjoyable when you are not exhausted or hungry by midnight, and the morning after feels a lot kinder.",
    "Respect for the neighbourhood makes a difference. Vagator is home to residents as well as revellers, so keep noise low as you return, avoid loud conversations near homes and follow local rules on music and closing times. Arrive quietly and the villa's pool will be waiting for a calm end to the night. Hosts and neighbours are far more welcoming to guests who leave a light footprint.",
  ],
  20: [
    "Quiet beaches reward preparation. Bring your own water, snacks and a sunshade, because facilities are sparser than on the busier strips, and take your rubbish with you. Early morning walks are a highlight, with soft light, cool sand and birds along the shoreline. If you enjoy photography, this is the time to shoot. By mid-morning the sun is strong, so plan a shaded lunch or a return to the pool, and keep hydrated.",
    "The best way to enjoy this stretch is to slow down. Spend one day at each beach, sample the local cafes and let the pace of the coast set your own. Avoid trying to fit everything in: a quiet holiday is about doing less, better. Evenings are calm too, with early dinners, starry skies and the sound of the sea, which is precisely why so many guests return year after year and bring friends.",
  ],
  21: [
    "Side dishes are worth as much attention as the main event. Order steamed rice or pao to mop up sauces, a simple salad to cut through spice and a cooling drink such as sol kadhi, made from coconut milk and kokum. Ask the kitchen about spice levels, since Goan food can be hot, and request milder versions if needed. Sharing dishes lets you sample far more of the menu than ordering individually.",
    "If you love the food, consider learning it. A market visit followed by a cooking session with a chef at your villa is a fun way to spend a slow afternoon, and you leave with recipes to try at home. Ask your caretaker whether your chef can teach a dish or two, and give notice so the right ingredients are ready. It is a memorable way to experience Goan cooking.",
  ],
  22: [
    "Peak season affects more than price. Restaurants fill up, traffic slows and popular beaches are lively from morning to night. That is part of the fun, but it helps to plan reservations for meals you care about and to build slack into travel days. Booking your villa early frees your attention for those details, so the trip feels organised rather than rushed, and you can enjoy the festive atmosphere.",
    "Keep your plans flexible where you can. If your dates are movable by a day or two, mention it when you enquire, since small changes can sometimes open up better availability. Clarify what is included, including housekeeping, the chef and airport transfers, and confirm payment dates in writing. A clear booking with no loose ends is the best gift you can give your future December self.",
  ],
  23: [
    "The enclave format works especially well for multi-family trips. Each family gets its own home, kitchen and pool, so routines do not clash: early risers are not woken by night owls, and children's bedtimes are respected. In the evenings, everyone can meet for dinner at whichever villa suits, then retreat to their own space. It is a way to travel together without the friction of sharing one house.",
    "The Anjuna–Vagator coast is easy to explore from here. Spend mornings at the beach, afternoons by your own pool and evenings at a cliff-top sunset or a market. Between outings, your caretaker keeps the home running so the days feel effortless. Compare the three villas' sizes and features before deciding, and remember that extra guests and events need prior approval.",
  ],
  24: [
    "Think about the ergonomics of your work setup, not just the connection. A proper table and chair, good light and somewhere quiet make far more difference than a view. If your villa has a dining table with a sturdy chair, you may be all set. Otherwise, ask what can be arranged in advance. Comfort matters for productivity, especially if you plan to work for several hours each day, and a small monitor or laptop stand can help.",
    "Balance is the point of a workation. Set a start and finish time, block out the working hours and protect the rest for the beach, food and rest. Many people find that mornings work best, with afternoons reserved for exploring. Stay hydrated, take breaks to swim or walk, and keep evenings offline. A good routine turns a working trip into a genuinely refreshing one.",
  ],
  25: [
    "Bring patience and curiosity. The market is busy, sometimes chaotic, and the pleasure lies in browsing without a fixed shopping list. Try small tastes, chat with stallholders and notice the everyday goods locals buy. It is a very different atmosphere from the more curated markets on the coast, and it gives a truer sense of how people in North Goa shop, cook and live day to day.",
    "Think about how you will carry your purchases. Terracotta and glass need careful wrapping, and spices travel best in sealed packs. Keep breakable items for the end of your trip and ask stallholders about wrapping. If you buy a lot, arrange a driver who can wait, and consider a stop for a snack in the town, where local bakeries and tea stalls make a good rest point.",
  ],
  26: [
    "A small celebration succeeds on detail. Decide the format — a lunch, a sundowner ceremony or a dinner — and build the guest experience around it. Lighting, seating, flowers and music make the mood, and a modest budget can go a long way in a good setting. Think about the weather too: evenings are pleasant, but sudden showers can appear in the shoulder season, so plan a covered fallback.",
    "Involve your caretaker early, since local knowledge helps with vendors, timings and small practicalities. Confirm the schedule for setup and cleanup so that nothing overlaps with check-in and check-out. Give guests clear directions and transport plans, and share the house rules with everyone attending. A well-briefed group makes for a smooth, relaxed celebration that the neighbours and the staff will remember fondly.",
  ],
  27: [
    "Golden hour is best enjoyed slowly. Arrive early, order a cold drink and watch the light change through orange, pink and violet. Bring a light layer for after sunset, because the sea breeze can cool quickly, and keep your phone charged for photographs. Some of the best moments happen after the sun disappears, when the sky glows and the crowds thin out around you.",
    "For a memorable evening, plan the whole arc: a late-afternoon swim, a walk to a viewpoint, a sundowner and a relaxed dinner. Leave time between each stage and avoid overbooking. If you are with a group, agree a plan for getting home safely and arrange a driver in advance, since taxis can be hard to find once the evening is in full swing.",
  ],
  28: [
    "To choose well, decide what mood you want: a quiet dinner for two, a lively group meal or a long, leisurely lunch. Assagao offers all three, and menus range from regional Indian to European-inspired. Read recent reviews with a critical eye, ask locals for suggestions and check whether a restaurant is open on the day you want, since smaller kitchens often close on one day of the week.",
    "Make dinner an occasion. Dress a little smarter than you would at the beach, arrive on time and take your time over the menu. Share plates, try the specials and leave room for dessert. Afterwards, walk or drive back through the village lanes, then end the night with a quiet swim at the villa. It is a tidy way to combine great food with a relaxed home base.",
  ],
  29: [
    "Do a quick test. Search for the property on a portal, note the total price including taxes and fees for your dates, then ask the property directly for a quote. Compare the two, along with the cancellation terms. Many travellers find the difference surprising, and if the direct rate is equal or lower, you also gain flexibility and a direct line to the people who will look after you.",
    "Trust is the fair question about booking direct, and the answer is transparency. Read the terms carefully, ask for the payment schedule in writing and check that the property has a real address, phone number and history. A reputable host will welcome your questions. If something changes later, you deal with the people who actually run the property, not a chain of intermediaries.",
  ],
  30: [
    "The value of a concierge is anticipation. Share your plans early, including arrival time, dietary needs, celebrations and mobility requirements, and the team can prepare before you arrive. A stocked kitchen, a chilled welcome drink or a birthday cake ready at the villa are small touches that set the tone for a trip. Good hospitality is mostly invisible planning done well in advance, and it makes the first evening feel effortless.",
    "When arranging outside experiences, use common sense. Choose licensed operators, read recent reviews and confirm timings, prices and what is included. Check the weather forecast for boat trips and be ready to reschedule if conditions are poor. Your caretaker can help with local knowledge, but the final booking is yours, so keep confirmations and contact numbers handy in case plans change.",
  ],
};

// A closing sentence or two appended to the outro of the shortest posts, so
// every post clears the 500-word floor with a comfortable margin. No links.
export const outroAdd: Record<number, string> = {
  1: "If Diwali plans are still forming, start with dates and headcount, then work outward to food, transport and celebrations. A short list of must-haves — pool, chef, quiet neighbourhood — makes it easy to choose quickly, and easier for our team to suggest the right home.",
  8: "Whichever estate you choose, share the group's dates, headcount and any special occasions early. That single conversation lets us confirm rooms, suggest meal plans and flag anything to arrange in advance, so the trip is smooth from arrival to departure.",
  9: "Whatever you decide, look at the whole picture rather than the brochure: how many people, how long, and what you want each day to feel like. The right answer becomes obvious once you write those three things down before you compare properties.",
  10: "Whatever kind of night you have in mind, plan the ride home first and the rest gets easier. Good evenings in Anjuna are relaxed, well paced and safe, and the villa's pool is the perfect finish to a long night out.",
  16: "Every visitor who follows these simple habits helps protect the nests and hatchlings that make this coast special. Travelling responsibly costs nothing, and it means the turtles can keep returning year after year for future guests to enjoy.",
  17: "Come with an appetite for slow days, long lunches and old stories. A heritage bungalow rewards guests who let the house set the pace, and it makes an unforgettable base for reunions, milestone birthdays and family holidays.",
  18: "Above all, be kind to yourself. A holiday with a toddler will not look like a holiday without one, and that is fine. Lower your expectations for the itinerary, protect the naps and let the pool and the garden do most of the entertaining.",
  19: "A circuit night is at its best when it feels unforced. Pick two or three stops rather than ten, enjoy the sunset properly and let the rest of the evening unfold. There is no prize for covering the most venues.",
  20: "Pack a good book, a wide-brimmed hat and no fixed agenda. The northern beaches reward visitors who linger, and a few unhurried days here often feel longer and more restorative than a whole week of sightseeing elsewhere on the coast.",
  25: "Go with an open mind and a light bag, and let the market surprise you. The best purchases are usually the ones you did not plan, and the memories of the crowds, colours and smells last far longer than any souvenir.",
  26: "The best celebrations are the ones that feel like the people at them. Choose a setting that fits your guest list rather than the other way round, keep the schedule relaxed and remember that small, thoughtful details are what guests will talk about afterwards.",
  27: "Golden hour comes around every evening, so there is no need to chase a perfect spot on day one. Try a different view each night, note your favourites and save the best table or terrace for your final sunset of the trip.",
  28: "Restaurants come and go, but Assagao's relaxed spirit stays the same. Go with an open mind, ask locals what they are enjoying this season and let one great meal lead to the next. A village that rewards curiosity is a rare thing.",
  29: "It takes a few minutes to compare prices and terms, and those minutes can save real money and hassle. Whichever way you book, read the cancellation policy and keep your confirmations safe so there are never any surprises at check-in.",
  30: "Above all, hospitality should feel effortless for the guest. If something can be arranged in advance, we would rather do it quietly beforehand than have you worry about it during your holiday, so tell us what would make your stay easier.",
};
